# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
COPY pyproject.toml uv.lock .
COPY math-server.py .
RUN pip install --upgrade pip && pip install .

CMD ["python", "math-server.py"]
